### ISSUE TITLE
No module named 'image_viewer'

### ISSUE THREAD

**Issue by magamig** [yinjunbo/UMA-MOT#6]
When running the test with `python test.py` in `Python 3.7.10`, it throws the following error:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import run_public
  File ".../UMA-MOT/UMA-TEST/run_public.py", line 5, in <module>
    from application_util import visualization
  File ".../UMA-MOT/UMA-TEST/application_util/visualization.py", line 6, in <module>
    from image_viewer import ImageViewer
ModuleNotFoundError: No module named 'image_viewer'
```
I've installed `image_viewer` with `pip` (although it was not on the requirements) - that didn't fix it.

**Comment by Dwj-njust** [comment]
File ".../UMA-MOT/UMA-TEST/application_util/visualization.py", line 6, in <module>
    from image_viewer import ImageViewer

" from image_viewer import ImageViewer" change to "from .image_viewer import ImageViewer"

**Comment by Dwj-njust** [comment]
"from image_viewer import ImageViewer" change to "from .image_viewer import ImageViewer"
